/* eslint-disable react-refresh/only-export-components */
export const InternetPackagesData = [
  {
    name: "Basic",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Starter",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Pro",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Premium",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Ultra",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Deluxe",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Super",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Mega",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Extreme",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Platinum",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Gold",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Silver",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Bronze",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Titanium",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Diamond",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Sapphire",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Ruby",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Emerald",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Crystal",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    name: "Basic",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
];

export const LpgGasData = [
  {
    picture:
      "https://images.unsplash.com/photo-1627881960266-52ffbc47aaa9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Z2FzJTIwY3lsaW5kZXJ8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=400&q=60",
    name: "Bashundhra Lpg",
    quantity: "12kg",
    valveSize: "20 M M",
    valveType: "Compact and Regular",
    Brand: "Bashundhara",
    publishDate: new Date(),
    price: 1800,
    offer: {
      isOffer: true,
      lessPrice: 50,
    },
    use: "Home and Household",
  },
  {
    picture:
      "https://images.unsplash.com/photo-1627881960266-52ffbc47aaa9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Z2FzJTIwY3lsaW5kZXJ8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=400&q=60",
    name: "Bashundhra Lpg",
    quantity: "30 kg",
    valveSize: "22 M M",
    valveType: "Compact and Regular",
    Brand: "Bashundhara",
    publishDate: new Date(),
    price: 1800,
    offer: {
      isOffer: false,
      lessPrice: 0,
    },
    use: "Commercial",
  },
  {
    picture:
      "https://images.unsplash.com/photo-1627881960266-52ffbc47aaa9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Z2FzJTIwY3lsaW5kZXJ8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=400&q=60",
    name: "jamuna Lpg",
    quantity: "12 kg",
    valveSize: "22 M M",
    valveType: "Compact and Regular",
    Brand: "JAMUNA",
    publishDate: new Date(),
    price: 1800,
    offer: {
      isOffer: false,
      lessPrice: 0,
    },
    use: "Home and Household",
  },
  {
    picture:
      "https://images.unsplash.com/photo-1627881960266-52ffbc47aaa9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Z2FzJTIwY3lsaW5kZXJ8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=400&q=60",
    name: "jamuna Lpg",
    quantity: "30 kg",
    valveSize: "22 M M",
    valveType: "Compact and Regular",
    Brand: "JAMUNA",
    publishDate: new Date(),
    price: 4000,
    offer: {
      isOffer: false,
      lessPrice: 0,
    },
    use: "Commercial",
  },
  {
    picture:
      "https://images.unsplash.com/photo-1664396113489-e50bddd4a777?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjR8fGdhcyUyMGN5bGluZGVyfGVufDB8fDB8fHww&auto=format&fit=crop&w=400&q=60",
    name: "Index Lpg",
    quantity: "30 kg",
    valveSize: "22 M M",
    valveType: "Compact and Regular",
    Brand: "INDEX",
    publishDate: new Date(),
    price: 3800,
    offer: {
      isOffer: false,
      lessPrice: 0,
    },
    use: "Commercial",
  },
  {
    picture:
      "https://images.unsplash.com/photo-1664396113489-e50bddd4a777?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjR8fGdhcyUyMGN5bGluZGVyfGVufDB8fDB8fHww&auto=format&fit=crop&w=400&q=60",
    name: "Index Lpg",
    quantity: "12 kg",
    valveSize: "22 M M",
    valveType: "Compact and Regular",
    Brand: "INDEX",
    publishDate: new Date(),
    price: 1800,
    offer: {
      isOffer: false,
      lessPrice: 0,
    },
    use: "Home and Household",
  },
  {
    picture:
      "https://images.unsplash.com/photo-1664396113489-e50bddd4a777?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjR8fGdhcyUyMGN5bGluZGVyfGVufDB8fDB8fHww&auto=format&fit=crop&w=400&q=60",
    name: "Omera Lpg",
    quantity: "30 kg",
    valveSize: "22 M M",
    valveType: "Compact and Regular",
    Brand: "OMERA",
    publishDate: new Date(),
    price: 1800,
    offer: {
      isOffer: false,
      lessPrice: 0,
    },
    use: "Commercial",
  },
  {
    picture:
      "https://images.unsplash.com/photo-1667487175121-caf8bd1b3619?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzl8fGdhcyUyMGN5bGluZGVyfGVufDB8fDB8fHww&auto=format&fit=crop&w=400&q=60",
    name: "Omera Lpg",
    quantity: "12 kg",
    valveSize: "22 M M",
    valveType: "Compact and Regular",
    Brand: "OMERA",
    publishDate: new Date(),
    price: 1800,
    offer: {
      isOffer: false,
      lessPrice: 0,
    },
    use: "Home and Household",
  },
  {
    picture:
      "https://images.unsplash.com/photo-1667487175121-caf8bd1b3619?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzl8fGdhcyUyMGN5bGluZGVyfGVufDB8fDB8fHww&auto=format&fit=crop&w=400&q=60",
    name: "BM Lp Gas",
    quantity: "12 kg",
    valveSize: "22 M M",
    valveType: "Compact and Regular",
    Brand: "BM Energy Bangladesh Ltd ",
    publishDate: new Date(),
    price: 1800,
    offer: {
      isOffer: false,
      lessPrice: 0,
    },
    use: "Home and Household",
  },
  {
    picture:
      "https://images.unsplash.com/photo-1667487175121-caf8bd1b3619?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzl8fGdhcyUyMGN5bGluZGVyfGVufDB8fDB8fHww&auto=format&fit=crop&w=400&q=60",
    name: "BM Lp Gas",
    quantity: "30 kg",
    valveSize: "22 M M",
    valveType: "Compact and Regular",
    Brand: "BM Energy Bangladesh Ltd ",
    publishDate: new Date(),
    price: 4000,
    offer: {
      isOffer: false,
      lessPrice: 0,
    },
    use: "Commercial",
  },
];

export const OilData = [
  {
    picture: "https://dailyshoppingbd.com/images/detailed/161/AAAAA.jpeg",
    name: "soyabin oil",
    brandName: "pusti",
    quantity: 1,
    price: 200,
    publishDate: new Date(),
    offer: {
      isOffer: true,
      lessPrice: 50,
    },
  },
  {
    picture: "https://dailyshoppingbd.com/images/detailed/161/AAAAA.jpeg",
    name: "soyabin oil",
    brandName: "pusti",
    quantity: 2,
    price: 400,
    publishDate: new Date(),
    offer: {
      isOffer: true,
      lessPrice: 50,
    },
  },
  {
    picture: "https://dailyshoppingbd.com/images/detailed/161/AAAAA.jpeg",
    name: "soyabin oil",
    brandName: "pusti",
    quantity: 5,
    price: 960,
    publishDate: new Date(),
    offer: {
      isOffer: true,
      lessPrice: 50,
    },
  },
  {
    picture:
      "https://images.deliveryhero.io/image/product-information-management/640dc1abd5795c467cf53c69.jpg?height=480",
    name: "soyabin oil",
    brandName: "Fresh",
    quantity: 1,
    price: 200,
    publishDate: new Date(),
    offer: {
      isOffer: true,
      lessPrice: 50,
    },
  },
  {
    picture:
      "https://images.deliveryhero.io/image/product-information-management/640dc1abd5795c467cf53c69.jpg?height=480",
    name: "soyabin oil",
    brandName: "Fresh",
    quantity: 2,
    price: 400,
    publishDate: new Date(),
    offer: {
      isOffer: true,
      lessPrice: 50,
    },
  },
  {
    picture:
      "https://images.deliveryhero.io/image/product-information-management/640dc1abd5795c467cf53c69.jpg?height=480",
    name: "soyabin oil",
    brandName: "Fresh",
    quantity: 5,
    price: 960,
    publishDate: new Date(),
    offer: {
      isOffer: true,
      lessPrice: 50,
    },
  },
  {
    picture:
      "https://i0.wp.com/www.khan.com.bd/wp-content/uploads/2020/10/Bashundara-Soyabean-Oil-Price-in-Mirpur.jpg?fit=1200%2C1200&ssl=1",
    name: "soyabin oil",
    brandName: "Bashundhara",
    quantity: 1,
    price: 200,
    publishDate: new Date(),
    offer: {
      isOffer: true,
      lessPrice: 50,
    },
  },
  {
    picture:
      "https://i0.wp.com/www.khan.com.bd/wp-content/uploads/2020/10/Bashundara-Soyabean-Oil-Price-in-Mirpur.jpg?fit=1200%2C1200&ssl=1",
    name: "soyabin oil",
    brandName: "Bashundhara",
    quantity: 2,
    price: 400,
    publishDate: new Date(),
    offer: {
      isOffer: true,
      lessPrice: 50,
    },
  },
  {
    picture:
      "https://i0.wp.com/www.khan.com.bd/wp-content/uploads/2020/10/Bashundara-Soyabean-Oil-Price-in-Mirpur.jpg?fit=1200%2C1200&ssl=1",
    name: "soyabin oil",
    brandName: "Bashundhara",
    quantity: 5,
    price: 960,
    publishDate: new Date(),
    offer: {
      isOffer: true,
      lessPrice: 50,
    },
  },
];

export const internetUsers = [
  {
    name: "mahmud",
    phoneNumber: "01671706882",
    email: "mahmud@gmail.com",
    address: "21/2,meradia,khilgaon,dhaka",
    serviceName: "internet",
    packageName: "Basic",
    PaymentInfo: [
      {
        MonthName: "January",
        status: true,
        billAmount: 500,
        DateOfBill: "16/9/2023",
      },
      {
        MonthName: "February",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "March",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "April",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "May",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "June",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "July",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "August",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "September",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "October",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "November",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "December",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
    ],
  },
  {
    name: "polash",
    phoneNumber: "01671706882",
    email: "polash@gmail.com",
    address: "21/2,meradia,khilgaon,dhaka",
    serviceName: "internet",
    packageName: "Basic",
    PaymentInfo: [
      {
        MonthName: "January",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "February",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "March",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "April",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "May",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "June",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "July",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "August",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "September",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "October",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "November",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
      {
        MonthName: "December",
        status: false,
        billAmount: 0,
        DateOfBill: "",
      },
    ],
  },
];
