export const InternetPackagesData = [
  {
    index: 1,
    name: "Basic",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 2,
    name: "Starter",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 3,
    name: "Pro",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 4,
    name: "Premium",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 5,
    name: "Ultra",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 6,
    name: "Deluxe",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 7,
    name: "Super",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 8,
    name: "Mega",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 9,
    name: "Extreme",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 10,
    name: "Platinum",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 11,
    name: "Gold",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 12,
    name: "Silver",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 13,
    name: "Bronze",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 14,
    name: "Titanium",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 15,
    name: "Diamond",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 16,
    name: "Sapphire",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 17,
    name: "Ruby",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 18,
    name: "Emerald",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 19,
    name: "Crystal",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
  {
    index: 20,
    name: "Basic",
    speed: 5,
    price: 500,
    vat: false,
    condition: ["No Security Deposit Required (for Any packages)"],
  },
];
